import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import * as React from "react";

export const Pokemon = gql`
  query {
    pokemon {
      id
      type
      name
      pokedex
    }
  }
`;

const Home: NextPage = () => {
  const pokemonData = useQuery(Pokemon);

  const pokemon = React.useMemo(() => {
    return pokemonData?.data;
  }, [pokemonData?.data]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {pokemon?.pokemon.map((i:any ) => {
            return (
             
                <a href="https://nextjs.org/docs" className={styles.card} key={i.id}>
                  <h2>{i.name}</h2>
                  <p>
                    {i.type}
                  </p>
                  <p>
                    {i.pokedex}
                  </p>
                </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
